export type SiteConfig = typeof siteConfig

export const siteConfig = {
  name: 'TFV',
  description:
    'TFV is a movie and tv show tracker built by Thith THIN. Based on Mohamed Gado template.',
  mainNav: [
    {
      title: 'Home',
      href: '/',
      scroll: true,
    },
    {
      title: 'Movies',
      href: '/movies',
      scroll: true,
    },
    {
      title: 'TV Shows',
      href: '/tv-shows',
      scroll: true,
    },
    {
      title: 'Watch History',
      href: '/watch-history',
      scroll: true,
    },
    {
      title: 'Disclaimer',
      href: '/disclaimer',
      scroll: false,
    },
  ],
  personalLogo: 'https://thith.vercel.app/me2.png',
  links: {
    twitter: 'https://twitter.com/ThithThin',
    github: 'https://github.com/thith-thith',
    website: 'https://thith.vercel.app/',
    buyMeACoffee: 'https://pay.ababank.com/UJ55vbWwJ5gGKCte9',
  },
  openGraph: {
    locale: 'en_US',
    type: 'website',
  },
  email: 'boogado@yahoo.com',
  websiteURL: 'https://www.reely.site',
  twitterTag: '@Sadge1996',
  image: 'https://thith.vercel.app/me2.png',
  keywords: [
    'TFV',
    'Reely',
    'TFV Site',
    'TFV Tracker',
    'Movie Tracker',
    'TV Show Tracker',
    'TFV Live',
    'Software Engineer',
    'Frontend Engineer',
    'Web Developer',
    'React',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'Mohamed Gado',
    'Thith',
    'Thith THIN',
    'React Developer',
    'React Engineer',
    'React.js',
    'ReactJS',
    'React Developer',
    'Next.js',
    'NextJS',
    'Next.js Developer',
    'Next.js Engineer',
  ],
}
